export const runtime = "nodejs";  // ← WICHTIG für PDFKit

import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";

export async function POST(req) {
  try {
    const body = await req.json();
    const { summary, chartBase64, metadata, kpis, schema, correlations } = body;

    const buffers = [];
    const doc = new PDFDocument({ size: "A4", margin: 40 });

    doc.on("data", (chunk) => buffers.push(chunk));
    doc.on("end", () => {});

    // HEADER -------------------------------------------------
    doc.rect(0, 0, doc.page.width, 70)
      .fillColor("#0B0B12")
      .fill();

    doc.fontSize(26).fillColor("#00eaff").text("UseClevr AI Report", 40, 20);
    doc.fontSize(12).fillColor("#9adfff").text("Automated Data Intelligence", 40, 50);

    doc.moveDown(2);

    // METADATA -----------------------------------------------
    doc.fontSize(14).fillColor("#00eaff").text("Dataset Information", { underline: true });

    doc.moveDown(0.3)
      .fontSize(11)
      .fillColor("#ffffff")
      .text(`Name: ${metadata.name}`)
      .text(`Rows: ${metadata.rows}`)
      .text(`Columns: ${metadata.columns}`)
      .moveDown(1);

    // SUMMARY -------------------------------------------------
    doc.fontSize(16).fillColor("#00eaff").text("AI Summary", { underline: true }).moveDown(0.5);

    doc.fontSize(11).fillColor("#ffffff")
      .text(summary || "No summary provided.", { align: "left" })
      .moveDown(1.5);

    // KPIs ----------------------------------------------------
    if (kpis?.length > 0) {
      doc.fontSize(16).fillColor("#00eaff").text("Key Metrics (KPIs)", { underline: true }).moveDown(0.8);

      const colWidth = (doc.page.width - 80) / 2;
      let x = 40;
      let y = doc.y;

      kpis.forEach((k, i) => {
        if (i % 2 === 0 && i !== 0) {
          x = 40;
          y += 80;
        }

        doc.rect(x, y, colWidth - 10, 70)
          .fillOpacity(0.1)
          .fillColor("#00eaff")
          .strokeColor("#00eaff")
          .lineWidth(0.5)
          .stroke();

        doc.fillColor("#ffffff").fontSize(12).text(
          `Column: ${k.column}
Sum: ${k.sum}
Avg: ${k.avg}
Min: ${k.min}
Max: ${k.max}
Anomalies: ${k.anomalies}`, x + 8, y + 6
        );

        x += colWidth;
      });

      doc.moveDown(5);
    }

    // SCHEMA ---------------------------------------------------
    if (schema?.length > 0) {
      doc.moveDown(1)
        .fontSize(16)
        .fillColor("#00eaff")
        .text("Schema Overview", { underline: true })
        .moveDown(0.8);

      schema.forEach((s) => {
        doc.rect(doc.x, doc.y, doc.page.width - 80, 50)
          .fillOpacity(0.1)
          .fillColor("#00eaff")
          .strokeColor("#00eaff")
          .stroke();

        doc.fillColor("#ffffff").fontSize(12).text(
          `Column: ${s.column}
Type: ${s.type}
Missing: ${s.emptyPercentage?.toFixed(1) || 0}%
Sample: ${s.sample || "—"}`,
          doc.x + 8,
          doc.y + 6
        );

        doc.moveDown(3);
      });

      doc.moveDown(1);
    }

    // CORRELATION ----------------------------------------------
    if (correlations && Object.keys(correlations).length > 0) {
      doc.fontSize(16).fillColor("#00eaff").text("Correlation Matrix", { underline: true }).moveDown(0.5);

      Object.keys(correlations).forEach((col) => {
        doc.fontSize(11).fillColor("#ffffff")
          .text(`${col}: ${JSON.stringify(correlations[col])}`)
          .moveDown(0.3);
      });

      doc.moveDown(1);
    }

    // CHART ------------------------------------------------------
    if (chartBase64) {
      const img = chartBase64.replace(/^data:image\/png;base64,/, "");
      const imgBuffer = Buffer.from(img, "base64");

      doc.addPage();

      doc.fontSize(18).fillColor("#00eaff").text("Data Visualization", { underline: true }).moveDown(1);

      doc.image(imgBuffer, { fit: [500, 350], align: "center" });
    }

    // FOOTER -----------------------------------------------------
    doc.moveDown(2)
      .fontSize(10)
      .fillColor("#9adfff")
      .text(`Generated by UseClevr • https://useclevr.com • ${new Date().toLocaleString()}`, {
        align: "center",
      });

    doc.end();

    const pdfBuffer = Buffer.concat(buffers);

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": "attachment; filename=useclevr_report.pdf",
      },
    });

  } catch (err) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
