import { NextResponse } from "next/server";
import OpenAI from "openai";
import PDFDocument from "pdfkit";
import { Readable } from "stream";

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

export async function POST(req) {
  try {
    const body = await req.json();
    const { dataset, kpis, schema, correlations } = body;

    // ---------------------------
    // BUILD AI PROMPT
    // ---------------------------
    const prompt = `
You are UseClevr AI, a senior data analyst.

Write a full multi-page narrative analysis based on:

DATASET (first 10 rows):
${JSON.stringify(dataset.slice(0, 10), null, 2)}

KPIs:
${JSON.stringify(kpis, null, 2)}

SCHEMA:
${JSON.stringify(schema, null, 2)}

CORRELATIONS:
${JSON.stringify(correlations, null, 2)}

Write the report using the following structure:

# EXECUTIVE SUMMARY
- Top 5 insights
- Key trends
- Main risks & opportunities

# KPI ANALYSIS
- Interpret each KPI
- Explain unusual values or anomalies

# CORRELATION INSIGHTS
- Mention strong correlations (>0.6)
- Mention strong negative correlations (< -0.4)
- Explain what these relationships could mean

# SCHEMA DIAGNOSTICS
- Missing values
- Data quality problems
- Columns that require cleaning

# OUTLIER ANALYSIS
- Identify which columns have outliers
- Explain potential reasons

# TREND ANALYSIS (if date column exists)
- Upward trends
- Downward trends
- Seasonal patterns

# RECOMMENDATIONS
- 5 data-driven suggestions for the business

Write the report professionally, concise, and formatted in clean paragraphs.
    `;

    // ---------------------------
    // CALL OPENAI
    // ---------------------------
    const ai = await client.chat.completions.create({
      model: "gpt-4.1",
      temperature: 0.2,
      messages: [
        { role: "system", content: "You are a senior data analyst." },
        { role: "user", content: prompt }
      ]
    });

    const narrative = ai.choices[0].message.content;

    // ---------------------------
    // BUILD PDF (MULTI-PAGE)
    // ---------------------------
    const doc = new PDFDocument({
      size: "A4",
      margin: 40
    });

    const stream = doc.pipe(new Readable().wrap(doc));

    // HEADER
    doc
      .rect(0, 0, doc.page.width, 60)
      .fillColor("#0B0B12")
      .fill();

    doc
      .fontSize(26)
      .fillColor("#00eaff")
      .text("UseClevr Narrative Report", 40, 15);

    doc.moveDown(2);

    // BODY TEXT
    doc
      .fontSize(12)
      .fillColor("#ffffff")
      .text(narrative, {
        align: "left"
      });

    doc.addPage();

    doc
      .fontSize(10)
      .fillColor("#9adfff")
      .text(
        `Generated by UseClevr • ${new Date().toLocaleString()}`,
        40,
        doc.page.height - 50,
        { align: "center" }
      );

    doc.end();

    const buffers = [];
    for await (const chunk of stream) buffers.push(chunk);

    const pdfBuffer = Buffer.concat(buffers);

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": "attachment; filename=narrative_report.pdf",
      },
    });

  } catch (err) {
    return NextResponse.json({ error: err.message });
  }
}
